/*
Extend the circuit you made in Task 2 by connecting one pushbutton to GP3 and
one to GP4.
Then, write a program with a blinking LED and program the pushbuttons to control
the blinking speed in the following way:
• When pushbutton on GP3 is pushed down, increase the blinking speed, so
that the LED blinks faster.
• When pushbutton on GP3 is pushed down, decrease the blinking speed, so
that the LED blinks slower.
*/